apiVersion: v2
name: inngest-server
description: Inngest Server Helm chart for Kubernetes
type: application
version: 1.1.4
appVersion: "v1.6.2"
icon: https://icoretech.github.io/helm/charts/inngest-server/logo.png
keywords:
  - inngest
  - serverless
  - event-driven
  - workflow
  - function-orchestration
  - async
  - queue
  - event-processing
  - background-jobs
  - microservices
  - faas
  - triggers
  - helm-chart
home: https://github.com/inngest/inngest
sources:
  - https://github.com/inngest/inngest
  - https://github.com/icoretech/helm/tree/main/charts/inngest-server
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/signKey: |
    fingerprint: D089525241C856C7D4A34A41DB4CF65A75647D87
    url: https://icoretech.github.io/helm/pgp-public-key.asc
  artifacthub.io/category: streaming-messaging
  artifacthub.io/deprecated: "true"
  artifacthub.io/deprecationMessage: "This Helm chart is deprecated because an official Inngest Helm chart is available at https://github.com/inngest/inngest-helm. Please use the official chart for new deployments and plan migrations from this one."
deprecated: true
