apiVersion: v2
name: inngest-server
description: Inngest Server Helm chart for Kubernetes
type: application
version: 1.0.9
appVersion: "1.5.7"
icon: https://icoretech.github.io/helm/charts/inngest-server/logo.png
keywords:
  - inngest
  - serverless
  - event-driven
  - workflow
  - function-orchestration
  - async
  - queue
  - event-processing
  - background-jobs
  - microservices
  - faas
  - triggers
  - helm-chart
maintainers:
  - name: Claudio Poli
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/inngest/inngest
sources:
  - https://github.com/inngest/inngest
  - https://github.com/icoretech/helm/tree/main/charts/inngest-server
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/redis
  artifacthub.io/category: monitoring-logging
