apiVersion: v2
name: chatgpt-retrieval-plugin
description: ChatGPT Retrieval Plugin Helm chart for Kubernetes
type: application
version: 0.0.21
appVersion: "0.0.1"
deprecated: true
keywords:
  - docker
  - openai
  - chatgpt
  - chatgpt-plugin
home: https://github.com/icoretech/chatgpt-retrieval-plugin-docker
sources:
  - https://github.com/icoretech/chatgpt-retrieval-plugin-docker
  - https://github.com/icoretech/helm/tree/main/charts/chatgpt-retrieval-plugin
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/signKey: |
    fingerprint: D089525241C856C7D4A34A41DB4CF65A75647D87
    url: https://icoretech.github.io/helm/pgp-public-key.asc
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/deprecated: "true"
  artifacthub.io/deprecationMessage: "This Helm chart is deprecated and no longer maintained by iCoreTech. No further support is planned; avoid new deployments and plan migrations."
# dependencies:
#   - name: redis-stack
#     version: "0.3.2"
#     repository: oci://registry-1.docker.io/bitnamicharts
#     condition: redis.enabled
