apiVersion: v2
name: pgbouncer
description: A Helm chart for deploying pgBouncer, a PostgreSQL connection pooler, on Kubernetes
type: application
version: 2.2.3
appVersion: 1.22.0
kubeVersion: ">= 1.20.0-0"
icon: https://icoretech.github.io/helm/charts/pgbouncer/logo.png
keywords:
  - pgBouncer
  - PostgreSQL
  - Kubernetes
maintainers:
  - name: Claudio Poli
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/icoretech/helm
sources:
  - https://github.com/icoretech/helm/tree/main/charts/pgbouncer
annotations:
  artifacthub.io/license: "MIT"
