apiVersion: v2
name: airbroke
description: Airbroke Helm chart for Kubernetes
type: application
version: 1.3.3
appVersion: "1.1.81"
keywords:
  - open
  - source
  - error
  - catcher
  - exception
  - monitoring
  - tracker
maintainers:
  - name: masterkain
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/icoretech/airbroke
sources:
  - https://github.com/icoretech/airbroke
  - https://github.com/icoretech/helm/tree/main/charts/airbroke
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/signKey: |
    fingerprint: D089525241C856C7D4A34A41DB4CF65A75647D87
    url: https://icoretech.github.io/helm/pgp-public-key.asc
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/icoretech/pgbouncer
  artifacthub.io/screenshots: |
    - title: Projects
      url: https://i.imgur.com/hcwnz84.png
    - title: Toolbox
      url: https://i.imgur.com/b2NBh2i.png
  artifacthub.io/category: monitoring-logging
dependencies:
  - name: pgbouncer
    version: "3.1.2"
    repository: oci://ghcr.io/icoretech/charts
    condition: pgbouncer.enabled
icon: https://icoretech.github.io/helm/charts/airbroke/logo.png
