apiVersion: v2
name: airbroke
description: Airbroke Helm chart for Kubernetes
type: application
version: 1.1.15
appVersion: "1.1.23"
keywords:
  - open
  - source
  - error
  - catcher
  - exception
  - monitoring
  - tracker
maintainers:
  - name: Claudio Poli
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/icoretech/airbroke
sources:
  - https://github.com/icoretech/airbroke
  - https://github.com/icoretech/helm/tree/main/charts/airbroke
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/icoretech/pgbouncer
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
  artifacthub.io/screenshots: |
    - title: Projects
      url: https://i.imgur.com/hcwnz84.png
    - title: Toolbox
      url: https://i.imgur.com/b2NBh2i.png
  artifacthub.io/category: monitoring-logging
dependencies:
  - name: pgbouncer
    version: "1.8.3"
    repository: oci://ghcr.io/icoretech/charts
    condition: pgbouncer.enabled
icon: https://icoretech.github.io/helm/charts/airbroke/logo.png
