apiVersion: v2
name: metamcp
description: MetaMCP aggregator Helm chart for Kubernetes
type: application
version: 0.1.23
appVersion: "latest"
icon: https://icoretech.github.io/helm/charts/metamcp/logo.png
keywords:
  - mcp
  - gateway
  - aggregator
maintainers:
  - name: Claudio Poli
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/icoretech/helm
sources:
  - https://github.com/icoretech/helm/tree/main/charts/metamcp
  - https://github.com/metatool-ai/metamcp
annotations:
  artifacthub.io/license: "MIT"
