apiVersion: v2
name: metamcp
description: MetaMCP aggregator Helm chart for Kubernetes
type: application
version: 0.2.4
appVersion: "2.4.22"
icon: https://icoretech.github.io/helm/charts/metamcp/logo.png
keywords:
  - mcp
  - gateway
  - aggregator
maintainers:
  - name: masterkain
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/icoretech/helm
sources:
  - https://github.com/icoretech/helm/tree/main/charts/metamcp
  - https://github.com/metatool-ai/metamcp
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/signKey: |
    fingerprint: D089525241C856C7D4A34A41DB4CF65A75647D87
    url: https://icoretech.github.io/helm/pgp-public-key.asc
