apiVersion: v2
name: nextjs
description: Generic Helm chart for Nextjs apps on Kubernetes
type: application
version: 1.1.17
appVersion: '1.0.0'
icon: https://icoretech.github.io/helm/charts/nextjs/logo.png
keywords:
  - nextjs
maintainers:
  - name: masterkain
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/icoretech/helm
sources:
  - https://github.com/icoretech/helm
annotations:
  artifacthub.io/license: 'MIT'
  artifacthub.io/signKey: |
    fingerprint: D089525241C856C7D4A34A41DB4CF65A75647D87
    url: https://icoretech.github.io/helm/pgp-public-key.asc
