apiVersion: v2
name: nextjs
description: Generic Helm chart for Nextjs apps on Kubernetes
type: application
version: 1.1.1
appVersion: '1.0.0'
keywords:
  - nextjs
maintainers:
  - name: Claudio Poli
    email: claudio@icorete.ch
    url: https://github.com/masterkain
home: https://github.com/icoretech/helm
sources:
  - https://github.com/icoretech/helm
annotations:
  artifacthub.io/license: 'MIT'
